---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 0
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: webserver-simple
        image: kostiscodefresh/summer-of-k8s-app:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080