apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-app
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: demo-app-rollout
  targetCPUUtilizationPercentage: 80
