---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  demo-app-mapping
spec:
  prefix: /demo/
  service: demo-app-service-stable
  resolver: endpoint
#   host: lab.local
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  demo-app-mapping-stable
spec:
  prefix: /stable/
  service: demo-app-service-stable
  resolver: endpoint
#   host: lab.local
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  demo-app-mapping-unstable
spec:
  prefix: /unstable/
  service: demo-app-service-canary
  resolver: endpoint
#   host: lab.local
