---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service-stable
  labels:
    app: demo-app  
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service-canary
  labels:
    app: demo-app 
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080            